// concert-app-react/src/components/App.jsx
import { useState } from "react";
import '../style/index.css'
import { Info } from "./Info";
import { useFetchConcert } from "../hooks/useFetchConcert";

function App() {
  
  const [resultConcert, setResultConcert] = useState([])
  const [index, setIndex] = useState(0)

  // USO API
  // const {concerts ,isLoading} = useFetchConcert(resultConcert)

  const concert = [
    {
      'id': 'c1',
      "concert": "Concert 1",
      "artist": "Reagan Bennett",
      "city": "Lillehammer",
      "image" : "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
      'id': 'c2',
      "concert": "Concert 2",
      "artist": "Malik Rice",
      "city": "Gatchina",
      "image": "https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
      'id': 'c3',
      "concert": "Concert 3",
      "artist": "Scott Dennis",
      "city": "Guadalajara",
      "image": "https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
      'id': 'c4',
      "concert": "Concert 4",
      "artist": "Scott Berg",
      "city": "Caxias do Sul",
      "image": "https://images.pexels.com/photos/167636/pexels-photo-167636.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
      'id': 'c5',
      "concert": "Concert 5",
      "artist": "Scott Berg",
      "city": "Gatchina",
      "image": "https://images.pexels.com/photos/167491/pexels-photo-167491.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    }
  ]

  let artistName, cityName = ''

  const onChangeName = (event)  =>{
    artistName = event.target.value    
  }

  const onChangeCity = (event)  =>{
    cityName = event.target.value    
  }

const search = () =>{
  let result=[]
  setIndex(1)
  if(artistName && !cityName){
    for (let index = 0; index < concert.length; index++) {
      if(concert[index].artist.includes(artistName)) result = [...result, concert[index]]
      setResultConcert(result)
    }
  }

  if(!artistName && cityName){
    for (let index = 0; index < concert.length; index++) {
      if(concert[index].city.includes(cityName)) result = [...result, concert[index]]
    }
    setResultConcert(result)
  }

  if(artistName && cityName){
    for (let index = 0; index < concert.length; index++) {
      if(concert[index].artist.includes(artistName) && concert[index].city.includes(cityName)){
        result = [...result, concert[index]]
      }
    }
    setResultConcert(result)
  }  
}

  return (
    <div>
      <h1>Search Concert</h1>
      <div className="form">
        <input type="text" placeholder="Artist" onChange={onChangeName} label='Artist'/>
        <input type="text" placeholder="City" onChange={onChangeCity} label='City'/>
        <button onClick={search}>Look for</button>    
      </div>
        {
            resultConcert.length>=1 ? 
              resultConcert.map((result) => {
                return(
                  <div key={result.id}>
                    <Info result={result} />
                  </div>
                )
            }) : (
              index!=0 && <p id="message-error-empty">Not found</p> 
              ) 
        }
          
            
        
    </div>
  )


  
}

export default App

// src/app/app.component.ts
import { Component,inject } from '@angular/core';
import { Concert } from './models/concert.model';
import {HttpClient} from '@angular/common/http'

//type Concert = Array<{ id: number; concert: string, artist:string,city:string,image:string }>;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})



export class AppComponent {
  title = 'concert-app';
  http= inject(HttpClient)

  // --------------CON API------------------
  // concerts: Concert[] = []

  // ngOnInit(){
  //   this.http.get<Concert[]>('https://api.escuelajs.co/api/v1/products')
  //     .subscribe((data)=>{
  //       this.concerts = data
  //     })
  // }

  // --------------SIN API------------------
  concerts: Concert[] = [
    {
      id: 1,
      concert: "Concert 1",
      artist: "Reagan Bennett",
      city: "Lillehammer",
      image : "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
      id: 2,
      concert: "Concert 2",
      artist: "Malik Rice",
      city: "Gatchina",
      image: "https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
      id: 3,
      concert: "Concert 3",
      artist: "Scott Dennis",
      city: "Guadalajara",
      image: "https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
      id: 4,
      concert: "Concert 4",
      artist: "Scott Berg",
      city: "Caxias do Sul",
      image: "https://images.pexels.com/photos/167636/pexels-photo-167636.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
      id: 5,
      concert: "Concert 5",
      artist: "Scott Berg",
      city: "Gatchina",
      image: "https://images.pexels.com/photos/167491/pexels-photo-167491.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    }
  ];

  artistName:string = ''
  cityName:string = ''

  res:Concert[] = []
  index:number = 0


  search(){
    this.index=1
    let result:any = []
    if(!this.artistName && !this.cityName){
      document.getElementById('message-error-empty')!.innerHTML='The fields are empty, please fill in to obtain more information'
    }else{
      document.getElementById('message-error-empty')!.innerHTML=''
    }

    if(this.artistName && !this.cityName){
      for (let index = 0; index < this.concerts.length; index++) {
        if(this.concerts[index].artist.includes(this.artistName)) {
          result = [...result, this.concerts[index]]
        }
        this.res=result
      }
    }
  
    if(!this.artistName && this.cityName){
      for (let index = 0; index < this.concerts.length; index++) {
        if(this.concerts[index].city.includes(this.cityName)) result = [...result, this.concerts[index]]
      }
      this.res=result
    }
  
    if(this.artistName && this.cityName){
      for (let index = 0; index < this.concerts.length; index++) {
        if(this.concerts[index].artist.includes(this.artistName) && this.concerts[index].city.includes(this.cityName)){
          result = [...result, this.concerts[index]]
        }
      }
      this.res=result
    }
  }

  handleClick(idNumber:number){
    let elementClick = document.getElementById(idNumber+'')    
    if(elementClick?.classList.contains('hidden')){
      elementClick.classList.remove('hidden')
      elementClick.classList.add('show')
    }else{
      elementClick?.classList.add('hidden')
      elementClick?.classList.remove('show')
    }
  }

  
}


<div class="body">
  <h1>Search Concert</h1>
  <div class="form">
    <input type="text" placeholder="Artist" label='Artist' [(ngModel)]="artistName"/>
    <input type="text" placeholder="City" label='City' [(ngModel)]="cityName"/>
    <button (click)="search()">Look for</button>    
  </div>

  <div *ngIf="res.length>=1;else message">
    <div id="result">
      <div class="info" *ngFor="let rest of res; let i = index" >
        <h3 (click)="handleClick(i)">{{rest.concert}}</h3>
        <div class="hidden" id={{i}}>
            <p><b>Artist:</b> {{rest.artist}}</p>
            <p><b>City:</b> {{rest.city}}</p>  
            <img src={{rest.image}}/>
        </div>
      </div>  
    </div>
  </div>

  <ng-template #message>
    <p id="message-error-empty" *ngIf="index!=0">Not found</p>
  </ng-template>
  
  <div class="message">
    <p id="message-error-empty"></p>
  </div>
  

  <!-- SI TENEMOS UNA API -->
  <!-- <app-concerts [concert]="concert" *ngFor="let concert of concerts">
    <h3 (click)="handleClick(i)">{{concert.concert}}</h3>
    <div class="hidden" id={{i}}>
        <p><b>Artist:</b> {{concert.artist}}</p>
        <p><b>City:</b> {{concert.city}}</p>  
        <img src={{concert.image}}/>
    </div>
  </app-concerts> -->

</div>
